### ISSUE TITLE
UnboundLocalError: local variable 's' referenced before assignment

### ISSUE THREAD

**Issue by 1065844566** [phydrus/phydrus#41] opened 2021-09-04 04:26 UTC
I get this error when I run example 2,3 and I don't know how to go about fixing it, looking for help!

runfile('D:/Source Code/python-hydrus/phydrus-master/phydrus-master/examples/example2.py', wdir='D:/Source Code/python-hydrus/phydrus-master/phydrus-master/examples')
INFO: Successfully wrote example2\SELECTOR.IN
INFO: Successfully wrote example2\PROFILE.DAT
INFO: Successfully wrote example2\ATMOSPH.IN
INFO: Hydrus-1D Simulation Successful.
Traceback (most recent call last):

  File "D:\Source Code\python-hydrus\phydrus-master\phydrus-master\examples\example2.py", line 48, in <module>
    df = ml.read_tlevel()

  File "C:\ProgramData\Anaconda3\lib\site-packages\phydrus\model.py", line 1417, in read_tlevel
    data = read_tlevel(path=path, usecols=usecols)

  File "C:\ProgramData\Anaconda3\lib\site-packages\phydrus\read.py", line 128, in read_tlevel
    data = _read_file(path=path, start="rTop", idx_col="Time",

  File "C:\ProgramData\Anaconda3\lib\site-packages\phydrus\decorators.py", line 12, in _check_file_path
    return function(path, *args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\phydrus\read.py", line 216, in _read_file
    data = read_csv(file, skiprows=s, nrows=e - s - 2, usecols=usecols,

UnboundLocalError: local variable 's' referenced before assignment

Thanks！

**Comment by 1065844566** [comment] 2021-09-04 11:26
I think I found where the problem is, my simulation results are faulty.

The T_LEVEL.OUT file is only 1kb, which is very different from the result in example 3, which is a full 200kb.

My T_LEVEL.OUT file is missing information such as rTop, which causes the function read_tlevelwu not to run properly.

I was thinking about where the root cause is and guessed that there might be a problem with the hydrus.exe generated via make.bat.

**Comment by martinvonk** [comment] 2021-09-04 14:08
This error warning generally occurs when the simulation crashes, and thus the T_LEVEL.OUT file is empty (1kb) and misses all information. Please check your model once again, maybe your discretization or boundary conditions are the cause of the problem.

If you can't find the error, feel free to share a notebook where the error occurs.

**Comment by 1065844566** [comment] 2021-09-05 01:09
> This error warning generally occurs when the simulation crashes, and thus the T_LEVEL.OUT file is empty (1kb) and misses all information. Please check your model once again, maybe your discretization or boundary conditions are the cause of the problem.
> 
> If you can't find the error, feel free to share a notebook where the error occurs.

Hi martinvonk，

Thank you for your reply. I tried again to re-fuse the source code to generate hydrus.exe and re-run the sample code, but it still reports the above error. Let me describe what I did, I put the make.bat file into the \scoure file directory and ran cmd (win10) in that directory. After that, running the make command in the cmd window shows the following: D:\Source Code\python-hydrus\source_code\source>gfortran HYDRUS.FOR INPUT.FOR HYSTER.FOR MATERIAL.FOR OUTPUT. FOR SINK.FOR SOLUTE.FOR TEMPER.FOR TIME.FOR WATFLOW.FOR -o "D:\Source Code\python-hydrus\source_code\source\\\hydrus.exe"
The size of the generated hydrus.exe is 403kb, I don't know if this value is correct.

If possible, can you provide me with a copy of the hydrus.exe you generated and I'll check if it's an error in that file.

Please send the file to email: 107556519106@stu.xju.edu.cn

Sincerely,

Lijing Han

**Comment by 1065844566** [comment] 2021-09-05 07:57
![bianliang](https://user-images.githubusercontent.com/63769573/132119191-4f1700f8-84d1-431a-b7a0-f8295efec009.png)
This is the picture of the variable explorer I got by running example 2. I can't find any errors.
![atm](https://user-images.githubusercontent.com/63769573/132119661-fa151d2c-0e26-4a40-8da7-04cbedb9275c.png)
![df](https://user-images.githubusercontent.com/63769573/132119668-7ef2a8d9-1be6-47c0-8620-ee3570f006ac.png)
![sol1](https://user-images.githubusercontent.com/63769573/132119693-b037bbc8-6c15-4c06-ab24-4089be22d7b7.png)
The variable **_sol1_** has no value in some of the columns inside, I'm not sure if this is an error, and I can't find where it is in all the .py files.

**Comment by 1065844566** [comment] 2021-09-07 01:04
The problem has been successfully solved!
The error is due to a problem with the production of hydrus.exe, although I do not know what the problem is?
I had previously installed the hydrus-1d package, so I pointed the run path to the H1D_CALC.EXE file under that package path. The program ran successfully!

**Comment by raoulcollenteur** [comment] 2021-10-06 21:27
Good to hear you fixed it! Closing issue :)

**Closed as completed by raoulcollenteur** 2021-10-06 21:27 UTC
Labels: question
